version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  plugins = ["react"]
  style_guide = "standard"

[[transformers]]
name = "prettier"
enabled = true

[[exclude_patterns]]
paths = ["src/lib/dayjs.ts"]
