# Runs all checks: JS/TS linting and Rust linting

name: Check All

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-js:
    name: Check JavaScript/TypeScript
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install dependencies from lockfile
        run: pnpm install --frozen-lockfile

      - name: Run lint step
        run: pnpm run lint

      - name: Check import order
        run: pnpm run format:imports

  check-rust:
    name: Check Rust
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Create empty 'dist' directory
        run: mkdir dist

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install dependencies from lockfile
        run: pnpm install --frozen-lockfile

      - name: Run rustfmt check
        run: pnpm format:rust:check

      - name: Run clippy check and deny warnings
        run: pnpm lint:rust

  check-tests:
    name: Run Tests
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install dependencies from lockfile
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
